general.import = [
  "~/.config/alacritty/themes/noctalia.toml",
  "~/.config/alacritty/appearance.toml",
  "~/.config/alacritty/osx.toml"
]

font = {
  normal = {
    family = "Hack Nerd Font Mono",
    style = "Regular",
  },
  bold = {
    style = "Bold"
  },
  bold_italic = {
    style = "Bold Italic"
  },
  italic = {
    style = "Italic"
  }
}
