# window and status colors
set-option -g @status_bg colour234

# set-option -g @bg_ssh     colour235
set-option -g @status_bg_ssh colour237

# window styles
set-option -g @window_style bg=colour234
set-option -g @w_active_style bg=colour0
set-option -g @w_active_style_ssh bg=colour235

## window-style disabled
# set-option -g @input_off "fg=colour240 bg=colour18"
set-option -g @input_off "fg=colour240 bg=colour232"
# set-option -g @input_on bg=colour234
set-option -g @input_on bg=colour234
set-option -g @w_active_style_off bg=colour237

# pane border styles
set-option -g @p_border_style fg=colour235,bg=colour234
set-option -g @p_active_border fg=colour235,bg=colour234
