set -g  @c_bg                    "colour238" # 
set -g  @c_bg_active             "colour0"   # #1C1C1C
set -g  @c_bg_disabled           "colour251" # 
set -g  @c_pane_border_bg        "colour235" # #262626

set -gF @c_bg_ssh                "#{@c_pane_border_bg}"

set -g @c_fg_disabled            "colour240" # #585858

# set -g @c_fg_ssh_text colour234

set -g  @c_active                "colour12" # #0000FF
set -gF @s_fg_active             "#[fg=#{@c_active}]"  # #0000FF

set -g  @c_bright_active         "colour39" # #00AFFF
set -g  @c_status_bg_ssh         "colour237" # #3A3A4A

set -g  @c_sync_panes_active     "colour208" # #FF8700
set -g  @c_sync_panes            "colour94"  # #875F00
# set -g  @c_sync_panes            "colour202" # # #FF5F00 


set -gF @s_sync_panes_active     "#[fg=#{@c_sync_panes_active}]" # #FF8700
set -gF @s_sync_panes            "#[fg=#{@c_sync_panes}]"        # #FF8700

set -gF @s_border_bg             "bg=#{@c_pane_border_bg}"

set -gF @s_p_active_border       "fg=#{@c_bright_active},#{@s_border_bg}"
set -gF @s_p_sync_active_border  "fg=#{@c_sync_panes},#{@s_border_bg}"
set -gF @s_p_border              "fg=#{@c_sync_panes},#{@s_border_bg}"

set-option -gF @s_p_border_style "fg=#{@c_status_bg_ssh},bg=#{@c_bg}"

set -gF @s_user_active           "#[bg=#{@c_active}]"
