# window styles
# set-option -g @window_style bg=colour234
# set-option -g @w_active_style bg=colour0
#
set-option -g  @window_style       bg=default
set-option -g  @w_active_style     bg=default
set-option -gF @w_active_style_ssh bg=default
# set-option -gF @w_active_style_ssh bg=colour235

## window-style disabled
set-option -gF @input_off "fg=#{@c_fg_disabled},bg=#{@c_bg_disabled}"
# set-option -gF @input_off "#{@c_input_off}"
set-option -gF @w_active_style_off bg="#{@c_status_bg_ssh}"

set-option -gF @mode_style "bg=cyan,fg=colour234,bold"

# 81 -> colour39
set-option -gF @p_active_border "#{@s_p_active_border}"

#########################
#     sane theming      #
#########################
# prefix indicator icon
set -g @icon "■"

%if "#{==:$SSH_CLIENT,}"
set -Fg status-bg "#{@c_bg}"
set -Fg window-active-style "#{@w_active_style}"
set -g status-position top
set -g pane-border-status top
%else
# override statusbg color in an ssh session
set -Fg status-bg "#{@c_status_bg_ssh}"
set -Fg window-active-style "#{@w_active_style_ssh}"
# set the bar on the bottom
set -g status-position bottom
set -g pane-border-status bottom
%endif

set -g status-style fg=white
set -g status-justify left

# set -g pane-border-lines heavy
set -g pane-border-lines heavy
set -g pane-border-indicators arrows

# Theme selection/copy mode highlight
set -gu mode-style
set -g mode-style "#{@mode_style}"

# Theme command prompt and error messages
set -gu message-style
# set -g message-style "bg=black,fg=brightgreen,bold"

# Theme command prompt history/info messages (bottom bar notifications)
set -gu message-command-style
# set -g message-command-style "bg=black,fg=yellow"

set -g pane-active-border "#{?pane_synchronized,#{E:@s_p_sync_border},#{E:@s_p_active_border}}"
set -g pane-border-style "#{?pane_synchronized,#{E:@s_p_sync_active_border},#{E:@s_p_border_style}}"

set -g status-left-length 32
set -g status-right-length 150
set -g status-interval 1

set -g window-style "#{@window_style}"

# show an orange icon when synchronize panes is on
set -g @prefix_button_syncpanes "#{?pane_synchronized,#{@s_sync_panes_active}#{@icon}, }#[default]"
set -g @prefix_button_highlight "#{?client_prefix,#{@s_fg_active}#{@icon},#{E:@prefix_button_syncpanes}}#[default]"
set -g @prefix_button "[#{E:@prefix_button_highlight}]"
set -g @user_section "#[bold]#{?client_prefix,#{@s_user_active}${USER},${USER}}#[default]"
set -gF @session_section "#{@s_active}#{session_name}#[default]"
set -g status-left "#{E:@prefix_button} #{E:@user_section} | #{@session_section} |  "

# set -g status-left '#(status-left)'
set -g status-right "#(status-right)"

set -g window-status-format "#(window-status-format)"
set -g window-status-current-format "#(window-status-current-format)"

set -g window-status-bell bg=default,fg=default
