#! /bin/sh

HEIGHT=10

systemctl --user start synergy.service

bspc config border_width         2
bspc config window_gap          12

bspc config -m focused top_padding "$HEIGHT"

bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_by_distance     true
bspc config history_aware_focus   true
bspc config focus_follows_pointer true

bspc monitor -a I II III IV V

# bspc rule -a Gimp desktop=^8 state=floating follow=on
# bspc rule -a Chromium desktop=^2
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
