#! /bin/sh
# local HEIGHT MONITORS

HEIGHT=10
LEMONBAR_PID="$XDG_RUNTIME_DIR/lemonbar/bar.py"

# systemctl --user start synergy.service
systemctl --user start synergyd.service

# clear any rules so that sourcing bspwmrc is idempotent
bspc rule -r '*:*'

# background
feh --bg-max $(randopaper.py) &

MONITOR_GAME="DVI-I-1"
MONITOR_MAIN="DP-2"
MONITOR_CHAT="DP-4"

MONITORS=$(xrandr -q | grep "*" | wc -l)

if [ "$MONITORS" -eq 3 ]; then
  bspc monitor "$MONITOR_GAME" -d 1 2
  bspc monitor "$MONITOR_MAIN" -d 3 4
  bspc monitor "$MONITOR_CHAT" -d 5 6
elif [ "$MONITORS" -eq 2 ]; then
  bspc monitor "$MONITOR_MAIN" -d 1 2 3
  bspc monitor "$MONITOR_CHAT" -d 4 5 6

  # remove detached
  bspc monitor "$MONITOR_GAME" -r
elif [ "$MONITORS" -eq 1 ]; then
  bspc monitor "$MONITOR_CHAT" -d 1 2 3 4 5 6
  bspc monitor "$MONITOR_MAIN" -r 2>/dev/null

  # remove detached
  bspc monitor "$MONITOR_GAME" -r
  bspc monitor "$MONITOR_MAIN" -r
fi

xargs kill -USR2 < $LEMONBAR_PID


bspc config focused_border_color \#3282B1
bspc config active_border_color \#052545
bspc config normal_border_color \#052545
bspc config presel_feedback_color \#3282B1
bspc config border_width         4
bspc config window_gap          24

bspc config pointer_motion_interval 15

bspc config top_padding "$HEIGHT"

bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true
# bspc config focus_by_distance     true
# bspc config history_aware_focus   true
bspc config focus_follows_pointer true
bspc config remove_disabled_monitors true


# steam
bspc rule -a Steam:Steam state=tiled
# if [ ! $(pgrep -i steam) ]; then
#   bspc rule -a Steam -o desktop=^2
# fi

# firestorm
bspc rule -a do-not-directly-run-firestorm-bin -o desktop=^5

# classname:instance_name
# fetch with $ bspc query -n @focused:/ -T | json_pp | less
# hangouts messenger
bspc rule -a Google-chrome:crx_knipolnnllmklapflnccelgolnpehhpl -o desktop=^4

if [ ! $(pgrep -i telegram) ]; then
  bspc rule -a TelegramDesktop -o desktop=^4
fi

bspc wm --adopt-orphans

# bspc rule -a Gimp desktop=^8 state=floating follow=on
# bspc rule -a Chromium desktop=^2
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
