#! /bin/sh
# local HEIGHT MONITORS

HEIGHT=10
LEMONBAR_PID="$XDG_RUNTIME_DIR/lemonbar/bar.py"

systemctl --user start synergy.service
systemctl --user start deluged.service

MONITORS=$(xrandr -q | grep "*" | wc -l)

if [ "$MONITORS" -eq 2 ]; then
  # DVI-I-3 = 1920x1200 | DVI-I-2 == 1600X900
  # bspc monitor DVI-I-3 -d I II III
  # bspc monitor DVI-I-2 -d IV V VI
  bspc monitor DVI-I-3 -d 1 2 3
  bspc monitor DVI-I-2 -d 4 5 6
elif [ "$MONITORS" -eq 1 ]; then
  # bspc monitor DVI-I-3 -r
  bspc monitor DVI-I-3 -r
  # bspc monitor DVI-I-2 -d 1 2 3 4 5 6
  bspc monitor DVI-I-2 -d 4 5 6 1 2 3

  # hoping there's more elegant solution to this...
  bspc desktop 1 -s 4
  bspc desktop 2 -s 5
  bspc desktop 3 -s 6
fi

xargs kill -USR2 < $LEMONBAR_PID


bspc config border_width         2
bspc config window_gap          12

bspc config top_padding "$HEIGHT"
bspc config window_gap 20

bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true
# bspc config focus_by_distance     true
# bspc config history_aware_focus   true
bspc config focus_follows_pointer true
bspc config remove_disabled_monitors true

DELUGE_PROC=$(pgrep -xf '/usr/bin/python2 /usr/bin/deluge')

# deluge
bspc rule -a Deluge -o desktop=^6

# firestorm
bspc rule -a do-not-directly-run-firestorm-bin -o desktop=^5

# classname:instance_name
# fetch with $ bspc query -n @focused:/ -T | json_pp | less
bspc rule -a Chromium:crx_knipolnnllmklapflnccelgolnpehhpl -o desktop=^4
bspc rule -a TelegramDesktop -o desktop=^4

systemctl --user start deluged
if [ -z "$DELUGE_PROC" ]; then
  nohup deluge  > /dev/null 2>&1 &
fi


bspc wm --adopt-orphans

# bspc rule -a Gimp desktop=^8 state=floating follow=on
# bspc rule -a Chromium desktop=^2
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off


# background
feh --bg-scale /home/seth/.wallpapers/neat.png &
