exec-once = $notify &
exec-once = push-to-talk -k KEY_F13 -n F13 /dev/input/by-id/usb-Logitech_USB_Receiver-if01-event-kbd &
exec-once = awww-daemon &
exec-once = systemctl --user start sunshine &
exec-once = ashell &
exec-once = dex -a
