# Set programs that you use
# See https://wiki.hypr.land/Configuring/Keywords/
$terminal = alacritty
$fileManager = dolphin
$browser = firefox
$menu = hyprlauncher
$notify = swaync
$bar = waybar

$mainMonitor = HDMI-A-1

# works!
$4k_default = '3840x2560@165'
$2k_default = '2560x1440@120'

$4k_mode = 'monitorv2[$mainMonitor]:mode' '$4k_default'
$2k_mode = 'monitorv2[$mainMonitor]:mode' '$2k_default'
