# See https://wiki.hypr.land/Configuring/Monitors/
# monitor=,preferred,auto,auto,

# monitor HDMI-A-1,1920x1080@144,0x0,1
# monitor = $2k

# $2k = monitor HDMI-A-1,2560x1440@144,0x0,1

# bind = SUPER, F8, exec, hyprctl keyword 'monitorv2[HDMI-A-1]:mode' '3840x2560@165'
bind = SUPER, F8, exec, hyprctl keyword $4k_mode
bind = SUPER, F9, exec, hyprctl keyword $2k_mode

bind = SUPER, F5, exec, hyprctl keyword 'monitorv2[$mainMonitor]:scale' '1'
bind = SUPER, F6, exec, hyprctl keyword 'monitorv2[$mainMonitor]:scale' '2'


monitorv2 {
    output = $mainMonitor
    # output = HDMI-A-1
    mode = 3840x2160@165
    # mode = 2560x1440@120
    position = 0x0
    vrr = 3
    # vrr = 2
    scale = 1

    ### hdr settings
    bitdepth = 10
    cm = hdr
    supports_hdr = 1
    supports_wide_color = 1
    min_luminance = 0.00
    max_luminance = 5000
    sdr_max_luminance = 200
    sdr_min_luminance = 0.105
    sdrbrightness = 1.0
    sdrsaturation = 1.0
}


# render: keep_unmodified_copy = 1
# keep_unmodified_copy
render {
    direct_scanout = 2
    cm_sdr_eotf = srgb
    non_shader_cm = 0
}
