windowrule {
    name = nte-floating-diags
    match:title = ^(?i)application\ hang\ detected*$
    tag = +floating
}

windowrule {
    match:title = ^(?i)NTEGlobalGame.*$
    no_initial_focus = on
    tag = +floating
}

windowrule {
    name = nte-vrr-flicker
    match:title = ^NTE.*$
    tag = +novrr
}
